document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title>Document</title>");
document.writeln("	<link rel=\'stylesheet\' href=\'css/head.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div class=\'top\'>");
document.writeln("	<div class=\'container pad\'>");
document.writeln("	<div class=\'row clearfix\'>");
document.writeln("		<div class=\'col-md-2\'>");
document.writeln("		<div class=\'logo\'>");
document.writeln("			<img src=\'images/logo.jpg\' alt=\'\'>");
document.writeln("		</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'col-md-7\'>");
document.writeln("		<div class=\'tnav\'>");
document.writeln("			<ul class=\'clearfix\'>");
document.writeln("				<li>");
document.writeln("				<a href=\'index.html\'>白象智造</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'chanp.html\'>产品家族</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'lichengb.html\'>白象里程碑</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'zer.html\'>企业社会责任</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'about.html\'>关于白象</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'col-md-3\'>");
document.writeln("		<div class=\'search vertical_container\'>");
document.writeln("			<form>");
document.writeln("				<span>搜索</span>");
document.writeln("				<input type=\'text\' placeholder=\'请输入关键词\'>");
document.writeln("				<button>");
document.writeln("					<img src=\'images/search.png\' alt=\'\'>");
document.writeln("				</button>");
document.writeln("			</form>");
document.writeln("		</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	</div>");
document.writeln("	</div>");
document.writeln("	<div id=\'lunb\'>");
document.writeln("		<form>");
document.writeln("			<button></button>");
document.writeln("			<button></button>");
document.writeln("			<button></button>");
document.writeln("		</form>");
document.writeln("	</div>");
document.writeln("	<script src=\'js/headJs.js\'></script>");
document.writeln("</body>");
document.writeln("</html>");